// Generated by Wrangler by running `wrangler types --x-include-runtime`

interface Env {
	JWT_SECRET: "secret";
	POSTGRES_USER: string;
	POSTGRES_PASSWORD: string;
	POSTGRES_DB: string;
	POSTGRES_HOST: string;
	DATABASE_URL: string;
}
